TOP:=../..
include $(TOP)/mk/std.mk

LIB:=eventmux
INCS:=eventmux.h
INCS+=eventselect.h
INCS+=eventio.h
INCS+=eventtimer.h
SRCS:=eventmux.c
SRCS+=eventselect.c
SRCS+=eventio.c
SRCS+=eventtimer.c
SRCS+=fdset.c

include $(TOP)/mk/lib.mk
